"use client";
import {useCallback,useEffect,useRef,useState,type CSSProperties} from "react";
import {ArrowUpRight,ArrowRight,ArrowDown,ArrowLeft,Plus,Minus,X,Menu} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";

type Photo={id:string;title:string;place:string;jp:string;tags:string[];description:string;position?:string};
const photos:Photo[]=[
{id:"kyoto",title:"Um momento em Quioto",place:"Quioto, Japão",jp:"京都",tags:["Quioto","Pessoas","Arquitetura","Templos"],description:"Um guarda-sol de papel, um lampejo de cor e uma rua silenciosa. Os menores gestos dão à cidade antiga o seu ritmo.",position:"60% 50%"},
{id:"fuji",title:"A forma do silêncio",place:"Monte Fuji, Japão",jp:"富士山",tags:["Natureza"],description:"Flores de cerejeira alcançam a água. Além delas, a montanha mantém seu lugar contra o céu do entardecer."},
{id:"osaka",title:"Sob as lanternas",place:"Shinsekai, Osaka",jp:"大阪",tags:["Osaka","Noite","Pessoas","Arquitetura"],description:"Letreiros disputam atenção enquanto a última luz azul se assenta entre os edifícios. A cidade muda lentamente de cor."},
{id:"autumn",title:"Uma estação em vermelhão",place:"Japão · paisagem de outono",jp:"秋",tags:["Natureza","Arquitetura"],description:"Uma ponte vermelha desaparece sob um dossel de ouro. Por uma breve estação, tudo parece brilhar por dentro."},
{id:"tokyo",title:"Tóquio, no limiar do dia",place:"Tóquio, Japão",jp:"東京",tags:["Tóquio","Noite","Arquitetura"],description:"A torre começa a brilhar sobre a cidade. Camada após camada, o horizonte se estende na suave cor do crepúsculo."},
{id:"onsen",title:"Onde o inverno exala",place:"Japão · paisagem de inverno",jp:"冬",tags:["Natureza","Pessoas"],description:"O vapor flutua sobre a água pálida e galhos cobertos de neve. A paisagem parece pausar entre o calor e o inverno."},
{id:"dotonbori",title:"A vida ao longo do canal",place:"Dōtonbori, Osaka",jp:"大阪",tags:["Osaka","Pessoas","Arquitetura"],description:"Um barco amarelo navega por um desfiladeiro de letreiros. Cores, reflexos e passos apressados se encontram ao redor do canal."},
{id:"bridge",title:"A luz entre as folhas",place:"Japão · paisagem fluvial",jp:"光",tags:["Natureza","Arquitetura"],description:"A luz baixa do sol desliza pelas árvores e toca a curva de uma ponte vermelha. O rio leva o momento adiante."},
{id:"kobe",title:"O porto torna-se azul",place:"Kobe, Japão",jp:"神戸",tags:["Noite","Arquitetura"],description:"O porto espelha um novo conjunto de cores à medida que o dia dá lugar à noite. Sobre a água, a cidade transforma-se em uma constelação."},
{id:"spring",title:"Um mundo de vapor nascente",place:"Japão · fontes termais",jp:"湯",tags:["Natureza","Templos"],description:"O vapor branco sobe em direção à vegetação verde e profunda. Um pequeno torii vermelho marca um vívido ponto de quietude na paisagem."},
{id:"snow",title:"Acima da floresta branca",place:"Japão · paisagem montanhosa",jp:"山",tags:["Natureza"],description:"Um teleférico vermelho flutua sobre uma floresta transformada pela neve. As formas familiares das árvores tornam-se algo de outro mundo."},
{id:"sakura",title:"Ao longo das águas da primavera",place:"Japão · temporada das cerejeiras",jp:"桜",tags:["Natureza"],description:"Ramos cor-de-rosa desenham a margem da água. Reflexos estendem-se até o horizonte, guardando as últimas cores da primavera."}
];
const categories=["Todas as fotografias","Tóquio","Quioto","Osaka","Natureza","Templos","Noite","Pessoas","Arquitetura"];
const navItems=[
{name:"Galeria",href:"#gallery"},
{name:"Histórias",href:"#stories"},
{name:"Lugares",href:"#places"},
{name:"Sobre",href:"#about"},
{name:"Contato",href:"#contact"}
];
const storySets=[
{title:"Quioto em Cores",eyebrow:"A tradição no cotidiano",ids:["kyoto","bridge","spring"]},
{title:"As Horas de Néon",eyebrow:"Quando as cidades ganham vida",ids:["tokyo","osaka","kobe","dotonbori"]},
{title:"Montanhas do Japão",eyebrow:"Uma sensação diferente de escala",ids:["snow","fuji","onsen"]},
{title:"Vapor & Silêncio",eyebrow:"Entre o inverno e o calor",ids:["onsen","spring","snow"]},
{title:"Ruas de Lanternas",eyebrow:"Seguindo a luz do entardecer",ids:["osaka","dotonbori","kyoto"]},
{title:"Uma Estação em Flor",eyebrow:"As cores que carregamos",ids:["sakura","fuji","autumn"]}
];
const image=(id:string)=>"/photos/"+id+".png";
const pad=(n:number)=>String(n).padStart(2,"0");
function PhotoButton({id,onOpen,className="",label=true}:{id:string;onOpen:(id:string)=>void;className?:string;label?:boolean}){
 const p=photos.find(p=>p.id===id)!;
 return <button className={"photo-button tilt "+className} data-cursor="Ver" onClick={()=>onOpen(id)} aria-label={"Ver "+p.title}>
 <img src={image(id)} alt={p.title} loading="lazy" width="612" height="408" style={{objectPosition:p.position}}/>
 {label&&<span className="photo-overlay"><span><span className="photo-location">{p.place}</span><strong>{p.title}</strong></span><span className="photo-plus"><Plus size={20}/></span></span>}</button>
}
export default function Home(){
 const [filter,setFilter]=useState("Todas as fotografias");
 const [selection,setSelection]=useState<{ids:string[];index:number;story?:string}|null>(null);
 const [zoom,setZoom]=useState(false),[menuOpen,setMenuOpen]=useState(false),[reduced,setReduced]=useState(false),[manualReduced,setManualReduced]=useState(false),[activeChapter,setActiveChapter]=useState("home");
 const cursor=useRef<HTMLDivElement>(null),cursorText=useRef<HTMLSpanElement>(null),lastFocus=useRef<HTMLElement|null>(null),touchStart=useRef<{x:number;y:number}|null>(null),nightTrack=useRef<HTMLDivElement>(null);
 const visible=photos.filter(p=>filter==="Todas as fotografias"||p.tags.includes(filter));
 const current=selection?photos.find(p=>p.id===selection.ids[selection.index])!:null;
 const openPhoto=useCallback((id:string,ids=photos.map(p=>p.id),story?:string)=>{lastFocus.current=document.activeElement as HTMLElement;setZoom(false);setSelection({ids,index:Math.max(0,ids.indexOf(id)),story})},[]);
 const nextPhoto=useCallback((delta:number)=>{setZoom(false);setSelection(s=>s?{...s,index:(s.index+delta+s.ids.length)%s.ids.length}:null)},[]);
 useEffect(()=>{const q=matchMedia("(prefers-reduced-motion: reduce)");const u=()=>setReduced(q.matches);u();q.addEventListener("change",u);return()=>q.removeEventListener("change",u)},[]);
 useEffect(()=>{document.documentElement.dataset.motion=(reduced||manualReduced)?"reduced":"full"},[reduced,manualReduced]);
 useEffect(()=>{if(!selection)return;const h=(e:KeyboardEvent)=>{if(e.key==="ArrowRight"){e.preventDefault();nextPhoto(1)}if(e.key==="ArrowLeft"){e.preventDefault();nextPhoto(-1)}};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[selection,nextPhoto]);
 useEffect(()=>{
 document.documentElement.classList.add("motion-ready");
 const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("revealed");o.unobserve(e.target)}}),{threshold:.07});
 document.querySelectorAll(".reveal").forEach(e=>o.observe(e));
 const c=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActiveChapter(e.target.id)}),{rootMargin:"-20% 0px -60% 0px"});
 document.querySelectorAll("[data-chapter]").forEach(e=>c.observe(e));
 return()=>{o.disconnect();c.disconnect()};
 },[]);
 useEffect(()=>{
 if(reduced||manualReduced)return;
 const fine=matchMedia("(pointer:fine)").matches;
 let frame=0,sf=0,tx=-100,ty=-100,x=-100,y=-100;
 const move=(e:PointerEvent)=>{tx=e.clientX;ty=e.clientY;const t=e.target as HTMLElement;const a=t.closest<HTMLElement>("[data-cursor],a,button");if(cursor.current){cursor.current.dataset.hover=a?"true":"false";cursor.current.dataset.visible="true";if(cursorText.current)cursorText.current.textContent=a?.dataset.cursor||(a?"↗":"")}const card=t.closest<HTMLElement>(".tilt");if(card&&fine){const r=card.getBoundingClientRect();card.style.setProperty("--rx",-((e.clientY-r.top)/r.height-.5)*5+"deg");card.style.setProperty("--ry",((e.clientX-r.left)/r.width-.5)*6+"deg")}};
 const out=(e:PointerEvent)=>{const c=(e.target as HTMLElement).closest<HTMLElement>(".tilt");if(c&&!c.contains(e.relatedTarget as Node)){c.style.setProperty("--rx","0deg");c.style.setProperty("--ry","0deg")}};
 const loop=()=>{x+=(tx-x)*.2;y+=(ty-y)*.2;if(cursor.current)cursor.current.style.transform="translate3d("+x+"px,"+y+"px,0)";frame=requestAnimationFrame(loop)};
 const paint=()=>{const y=scrollY;document.documentElement.style.setProperty("--scroll-progress",y/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100+"%");document.querySelector(".site-header")?.classList.toggle("scrolled",y>50);document.querySelectorAll<HTMLElement>("[data-parallax]").forEach(el=>{const b=el.parentElement!.getBoundingClientRect();if(b.bottom>0&&b.top<innerHeight)el.style.setProperty("--parallax",(innerHeight/2-b.top-b.height/2)*Number(el.dataset.parallax)+"px")});sf=0};
 const scroll=()=>{if(!sf)sf=requestAnimationFrame(paint)};
 if(fine){window.addEventListener("pointermove",move);window.addEventListener("pointerout",out);frame=requestAnimationFrame(loop)}
 window.addEventListener("scroll",scroll,{passive:true});paint();
 return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerout",out);window.removeEventListener("scroll",scroll);cancelAnimationFrame(frame);cancelAnimationFrame(sf)};
 },[reduced,manualReduced]);
 return <>
 <a href="#gallery" className="skip-link">Pular para a coleção</a>
 <div ref={cursor} className="custom-cursor" aria-hidden="true"><span ref={cursorText}/></div><div className="reading-progress" aria-hidden="true"/>
 <header className="site-header"><a className="wordmark" href="#home" aria-label="Hanzi início">hanzi<span className="brand-dot"/></a><nav aria-label="Navegação principal" className="desktop-nav">{navItems.map(item=><a key={item.href} href={item.href}>{item.name}</a>)}</nav><a className="header-cta" href="#gallery">Explorar o Japão <ArrowUpRight size={16}/></a><button className="menu-toggle" onClick={()=>setMenuOpen(true)} aria-label="Abrir navegação"><Menu size={24}/></button></header>
 <main>
 <section className="hero" id="home" data-chapter><button className="hero-background" data-cursor="Ver" onClick={()=>openPhoto("kyoto")} aria-label={"Ver "+photos.find(p=>p.id==="kyoto")!.title}><img src={image("kyoto")} alt="Um guarda-sol colorido em uma rua tradicional de Quioto" fetchPriority="high" width="612" height="408"/></button><div className="hero-shade"/><div className="hero-topline"><span>Uma jornada fotográfica pelo Japão</span><span>Coleção independente / Vol. 01</span></div><div className="hero-title"><h1 aria-label="Hanzi">{"HANZI".split("").map((letter,i)=><span key={i} style={{"--i":i} as CSSProperties}>{letter}</span>)}</h1><div className="hero-subtitle"><span className="red-stroke"/>Histórias Através da Luz<span className="hero-jp">写真で旅する日本</span></div></div>
 <div className="hero-bottom"><div className="hero-copy"><p>Ruas antigas. Montanhas silenciosas.<br/>Mil maneiras de ver o Japão.</p><a className="text-link" href="#gallery">Explorar a Coleção <ArrowUpRight size={21}/></a></div><a className="journey-link" href="#collection"><span className="round-arrow"><ArrowDown size={20}/></span><span>Iniciar a jornada<br/><small>Role para descobrir</small></span></a><div className="hero-contact-sheet"><div className="film-index"><span>01 / 12</span><span>日本 — 2026</span></div><div className="film-photos">{["kyoto","fuji","osaka"].map((id,i)=><button data-cursor="Ver" onClick={()=>openPhoto(id)} key={id} aria-label={"Ver "+photos.find(p=>p.id===id)!.title}><img src={image(id)} alt=""/><span>{pad(i+1)}</span></button>)}</div><span className="film-caption">Um momento em Quioto <span>京都</span></span></div></div><div className="hero-edge">DESCUBRA O JAPÃO ATRAVÉS DE MOMENTOS, LUGARES E LUZ.</div></section>
 <section className="collection section-pad" id="collection" data-chapter><div className="section-heading reveal"><span className="eyebrow"><i/>01 — A coleção</span><span className="micro">Um diário visual em evolução</span></div><div className="intro-grid"><h2 className="display reveal">Japão<br/>em <em>Quadros.</em></h2><div className="intro-copy reveal"><span className="jp-heading" lang="ja">一瞬を、永遠に。</span><p>Entre o silêncio e o movimento, a tradição e a modernidade, cada imagem revela um Japão diferente.</p><p className="muted">Uma coleção de lugares, luz fugaz e momentos que merecem ser contemplados com mais calma.</p><a href="#gallery" className="text-link">Descubra a coleção <ArrowUpRight size={19}/></a></div></div><div className="editorial-grid"><figure className="editorial-main reveal"><PhotoButton id="bridge" onOpen={openPhoto}/><figcaption><span>01 / A LUZ ENTRE AS FOLHAS</span><span>日本</span></figcaption></figure><div className="editorial-side reveal"><span className="vertical-word" aria-hidden="true">MOMENTOS, NÃO DISTÂNCIAS.</span><PhotoButton id="kyoto" onOpen={openPhoto}/><p>Certos lugares ficam com você.<br/><em>Alguns momentos nunca se vão.</em></p></div></div></section>
 <section className="gallery-section section-pad" id="gallery" data-chapter><div className="gallery-heading reveal"><div><span className="eyebrow"><i/>O arquivo visual</span><h2 className="display">Um olhar mais <em>atento.</em></h2></div><span className="archive-count">12 <span>fotografias<br/>selecionadas</span></span></div><div className="filters" role="group" aria-label="Filtrar fotografias">{categories.map(cat=><button key={cat} onClick={()=>setFilter(cat)} aria-pressed={filter===cat} className={filter===cat?"active":""}>{cat}{cat==="Todas as fotografias"&&<sup>12</sup>}</button>)}</div><p className="sr-only" role="status">{visible.length} fotografias em {filter}</p><div className={"gallery-grid "+(visible.length<3?"short-grid":"")} key={filter}>{visible.map((p,i)=><figure className="gallery-item" key={p.id} style={{"--i":i} as CSSProperties}><PhotoButton id={p.id} onOpen={id=>openPhoto(id,visible.map(p=>p.id))}/><figcaption><span><span className="photo-number">{pad(photos.indexOf(p)+1)}</span>{p.title}</span><span lang="ja">{p.jp}</span></figcaption></figure>)}</div><div className="archive-end"><span>Cada quadro, um sentimento diferente.</span><span>{pad(visible.length)} fotografias / {filter}</span></div></section>
 <section className="night-section" id="places" data-chapter><div className="night-heading section-pad reveal"><span className="eyebrow"><i/>02 — Uma cidade que nunca dorme</span><h2 className="display">Tóquio<br/><em>Ao Anoitecer.</em></h2><span className="night-jp" lang="ja">東京の夜</span><p>Luzes de néon, reflexos, movimento e silêncio.<br/>Um mundo diferente começa ao cair do dia.</p></div><div className="night-panorama reveal"><img data-parallax=".10" src={image("tokyo")} alt="Torre de Tóquio brilhando sobre a cidade ao pôr do sol" loading="lazy"/><button className="image-open" onClick={()=>openPhoto("tokyo")} data-cursor="Ver" aria-label="Ver Tóquio no limiar do dia"><Plus size={22}/></button><span className="panorama-caption">TÓQUIO — 東京 <span>A HORA AZUL</span></span></div><div className="night-footer section-pad"><div className="night-strip-title"><span className="eyebrow">Além de Tóquio</span><h3>Siga a <em>luz.</em></h3><div className="track-arrows"><button aria-label="Fotografias anteriores" onClick={()=>nightTrack.current?.scrollBy({left:-420,behavior:reduced||manualReduced?"instant":"smooth"})}><ArrowLeft/></button><button aria-label="Próximas fotografias" onClick={()=>nightTrack.current?.scrollBy({left:420,behavior:reduced||manualReduced?"instant":"smooth"})}><ArrowRight/></button></div></div><div className="night-track" ref={nightTrack}>{["osaka","kobe","dotonbori"].map(id=><figure key={id}><PhotoButton id={id} onOpen={openPhoto}/><figcaption>{photos.find(p=>p.id===id)!.place}</figcaption></figure>)}</div></div></section>
 <section className="quiet-section section-pad" id="quiet" data-chapter><div className="section-heading reveal"><span className="eyebrow"><i/>03 — Um ritmo mais sereno</span><span lang="ja">静かな日本</span></div><div className="quiet-intro"><h2 className="display reveal">O Japão<br/><em>Silencioso.</em></h2><p className="reveal">Além do néon, outro Japão se revela — sereno, atemporal e profundamente enraizado na natureza.</p></div><div className="quiet-grid"><figure className="quiet-large reveal"><PhotoButton id="onsen" onOpen={openPhoto}/><figcaption>INVERNO, SUAVE. <span>日本の冬</span></figcaption></figure><figure className="quiet-small reveal"><PhotoButton id="autumn" onOpen={openPhoto}/><figcaption>A COR DA PASSAGEM DO TEMPO.</figcaption><p>Ouça os espaços<br/><em>entre os momentos.</em></p></figure></div></section>
 <section className="fuji-section" id="fuji" data-chapter><img className="fuji-image" data-parallax=".15" src={image("fuji")} alt="Monte Fuji além de um lago e cerejeiras cor-de-rosa em flor" loading="lazy"/><div className="fuji-shade"/><div className="fuji-top"><span>35.3606° N — 138.7274° E</span><span>04 — A montanha eterna</span></div><div className="fuji-title reveal"><span lang="ja">富士山</span><h2>FUJI</h2></div><div className="fuji-bottom"><p>Uma silhueta sagrada que moldou<br/>a imaginação do Japão por séculos.</p><button onClick={()=>openPhoto("fuji")} className="text-link" data-cursor="Ver">Ver fotografia <Plus size={19}/></button></div></section>
 <section className="stories-section section-pad" id="stories" data-chapter><div className="gallery-heading reveal"><div><span className="eyebrow"><i/>05 — Notas da jornada</span><h2 className="display">Histórias <em>Visuais.</em></h2></div><p>Um lugar. Alguns quadros.<br/>Uma história própria.</p></div><div className="stories-grid">{storySets.map((s,i)=><button key={s.title} className="story-card tilt reveal" data-cursor="Explorar" onClick={()=>openPhoto(s.ids[0],s.ids,s.title)}><span className="story-image"><img src={image(s.ids[0])} alt="" loading="lazy"/><span className="story-image-count">{pad(s.ids.length)} QUADROS</span></span><span className="story-topline"><span>HISTÓRIA {pad(i+1)}</span><ArrowUpRight size={20}/></span><h3>{s.title}</h3><p>{s.eyebrow}</p></button>)}</div></section>
 <section className="about-section section-pad" id="about" data-chapter><div className="about-mark" aria-hidden="true">光</div><div className="about-copy reveal"><span className="eyebrow"><i/>Sobre o Hanzi</span><h2>Uma maneira de<br/><em>olhar.</em></h2><p>Hanzi é uma jornada visual por ruas antigas, montanhas silenciosas, cidades em néon e momentos efêmeros do dia a dia. Um convite para desacelerar, olhar mais de perto e descobrir o Japão através da luz.</p><span className="micro">Coleção fotográfica independente · 2026</span></div></section>
 <section className="closing"><img data-parallax=".08" src={image("bridge")} alt="Luz suave do sol sobre uma ponte vermelha no Japão" loading="lazy"/><div className="closing-shade"/><div className="closing-copy reveal"><span className="eyebrow">Leve um momento com você</span><h2>O Japão não é apenas um lugar<br/>que se visita.</h2><p>É uma coleção de momentos que você carrega consigo.</p><a className="text-link" href="#gallery">Explorar Todas as Fotografias <ArrowUpRight size={22}/></a></div></section>
 <footer className="site-footer section-pad" id="contact"><div className="footer-top"><div><a className="wordmark" href="#home">hanzi<span className="brand-dot"/></a><p>Fotografia do Japão</p></div><div className="footer-links"><a href="#gallery">Galeria</a><a href="#stories">Histórias</a><a href="#about">Sobre</a></div><div className="footer-contact"><span className="eyebrow">Contato & redes</span><p>Informações de contato e perfil do Instagram<br/>não estão listados para esta coleção.</p></div><span className="footer-jp" lang="ja">日本</span></div><div className="footer-bottom"><span>© 2026 Hanzi — Histórias Através da Luz</span><button onClick={()=>setManualReduced(v=>!v)} aria-pressed={reduced||manualReduced}>Movimento: {reduced||manualReduced?"reduzido":"completo"}</button><a href="#home">Voltar ao topo <ArrowUpRight size={15}/></a></div></footer>
 </main>
 <aside className="chapter-rail" aria-label="Capítulos da jornada">{[{id:"home",label:"Início"},{id:"collection",label:"Coleção"},{id:"gallery",label:"Galeria"},{id:"places",label:"Cidades"},{id:"quiet",label:"Japão Sereno"},{id:"fuji",label:"Fuji"},{id:"stories",label:"Histórias"}].map(c=><a href={"#"+c.id} key={c.id} aria-label={c.label} aria-current={activeChapter===c.id?"location":undefined} className={activeChapter===c.id?"active":""}><span>{c.label}</span></a>)}</aside>
 <Dialog open={!!selection} onOpenChange={v=>{if(!v){setSelection(null);setZoom(false)}}}><DialogContent className="lightbox" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();lastFocus.current?.focus({preventScroll:true})}}>
 {current&&selection&&<><div className="lightbox-top"><span className="lightbox-brand">hanzi<span className="brand-dot"/></span><span>{selection.story||"A coleção"} <span className="muted">/ {pad(selection.index+1)} — {pad(selection.ids.length)}</span></span><button className="icon-button" aria-label="Fechar fotografia" onClick={()=>setSelection(null)}><X/></button></div><div className={"lightbox-stage "+(zoom?"is-zoomed":"")} onTouchStart={e=>{touchStart.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(touchStart.current&&!zoom){const dx=e.changedTouches[0].clientX-touchStart.current.x,dy=e.changedTouches[0].clientY-touchStart.current.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy))nextPhoto(dx<0?1:-1)}touchStart.current=null}}><button className="lightbox-prev icon-button" aria-label="Fotografia anterior" onClick={()=>nextPhoto(-1)}><ArrowLeft/></button><div className="lightbox-image-scroll"><button className="lightbox-image-button" aria-label={zoom?"Reduzir zoom da fotografia":"Ampliar fotografia"} onClick={()=>setZoom(v=>!v)}><img key={current.id} src={image(current.id)} alt={current.title}/></button></div><button className="lightbox-next icon-button" aria-label="Próxima fotografia" onClick={()=>nextPhoto(1)}><ArrowRight/></button><button className="lightbox-zoom icon-button" aria-label={zoom?"Reduzir zoom":"Ampliar"} onClick={()=>setZoom(v=>!v)}>{zoom?<Minus/>:<Plus/>}</button></div><div className="lightbox-info" aria-live="polite"><div><span className="eyebrow">{current.place}</span><DialogTitle className="lightbox-title">{current.title}</DialogTitle><DialogDescription className="lightbox-description">{current.description}</DialogDescription></div><dl><div><dt>Data</dt><dd>Não informada</dd></div><div><dt>Câmera</dt><dd>Não informada</dd></div><div><dt>Lente</dt><dd>Não informada</dd></div></dl></div><div className="lightbox-bottom"><span>← → para navegar <span className="desktop-only">· ESC para fechar</span><span className="mobile-only">· deslize para navegar</span></span><span lang="ja">{current.jp}</span></div></>}
 </DialogContent></Dialog>
 <Dialog open={menuOpen} onOpenChange={setMenuOpen}><DialogContent className="mobile-menu" showCloseButton={false}><DialogTitle className="sr-only">Navegação</DialogTitle><DialogDescription className="sr-only">Explore a coleção Hanzi</DialogDescription><button className="menu-close icon-button" aria-label="Fechar navegação" onClick={()=>setMenuOpen(false)}><X/></button><span className="eyebrow">Hanzi — Histórias Através da Luz</span>{navItems.map((x,i)=><a key={x.href} href={x.href} onClick={()=>setMenuOpen(false)}><span>{pad(i+1)}</span>{x.name}<ArrowUpRight/></a>)}<span lang="ja">日本</span></DialogContent></Dialog>
 </>;
}
